import Head from "next/head";
import Image from "next/image";
import InputForm from "../components/InputForm";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>BioInformatics Project</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <InputForm />
    </div>
  );
}
